#!/bin/sh
#jss - jenkins support scripts http://safrm.net/projects/jss
#author: Miroslav Safr <miroslav.safr@gmail.com>
#update rpm repos with default deleting policy
#
#exported GPGKEY or first key is used for signing
VERSION=NA                                                                   
VERSION_DATE=NA

KEEP_PKGS=2
EXIT_CODE=0
while [ $# -gt 0 ]; do
  case "$1" in
    -v|--verbose)
               VERBOSE=1
               ;;
	-n|--name) shift;
			SIGN_NAME=$1
			;;
	* )    REPO_DIR=$1;
	       ;;
  esac
  shift
done


#check parameter
if [ -z "$REPO_DIR" ];	then
	REPO_DIR=`pwd`
fi

if [ ! -d "$REPO_DIR" ];	then
	echo "not existing dir $REPO_DIR, exiting.."
	exit 1
fi

if [ -z "$SIGN_NAME" ]; then
	echo "signing name has to be defined, exiting..."
	exit 1
fi

#first key if not defined
if [ -z "$GPGKEY" ]; then
	echo "getting first GPGKEY.."
	GPGKEY=`gpg --list-keys |  grep "pub " | awk -F "[ /]" '{print $5}' | head -1`
fi
if [ -z "$GPGKEY" ]; then
	echo "GPGKEY not found, exiting..."
	exit 1
fi
GPG_NAME=`gpg --list-keys | grep "$GPGKEY" -1 | grep uid | sed "s/uid *//"`

#clean up
rm -f $REPO_DIR/Packages $REPO_DIR/Packages.gz $REPO_DIR/Sources $REPO_DIR/Sources.gz $REPO_DIR/Release $REPO_DIR/InRelease $REPO_DIR/Release.gpg 


#check signs
jss-debrepo-signcheck $REPO_DIR
if [ $? -ne 0 ]; then
	echo "not sign packages in repo - resigning"
	PACKAGES=`find $REPO_DIR -type f -printf '%p\n' | grep -i -E -Z '\.(deb|changes)$'`
	echo "${PACKAGES}" | \
	{ while IFS='\n' read -r ENTRY ;
	do
		echo "test:$ENTRY"
		RES=`dpkg-sig -c $ENTRY | grep $GPGKEY`
		if [ $? -ne 0 ]; then
			"signing> $SIGN_NAME KEY:$GPGKEY FILE:$ENTRY"
			dpkg-sig -s $SIGN_NAME -k $GPGKEY $ENTRY
	  	fi
	done
	}
else 
echo "jss-debrepo-signcheck=0"
fi

#recreate
dpkg-scanpackages  $REPO_DIR/ /dev/null  >   $REPO_DIR/Packages
cat $REPO_DIR/Packages | gzip -9 >  $REPO_DIR/Packages.gz 
dpkg-scansources  $REPO_DIR/  >  $REPO_DIR/Sources
cat $REPO_DIR/Sources | gzip -9 >  $REPO_DIR/Sources.gz 

#release sign
apt-ftparchive release $REPO_DIR > $REPO_DIR/Release
gpg --clearsign -o $REPO_DIR/InRelease $REPO_DIR/Release
gpg -abs -o $REPO_DIR/Release.gpg $REPO_DIR/Release


