#!/bin/sh
#jss - jenkins support scripts http://safrm.net/projects/jss
#author: Miroslav Safr <miroslav.safr@gmail.com>
#update rpm repos with default deleting policy
#
#exported GPGKEY or first key is used for signing

REPO_DIR=$1
KEEP_PKGS=2

#check parameter
if [ -z "$1" ];	then
	echo "missing repo dir argument, exiting.."
	exit 1
fi

if [ ! -w "$1" ];	then
	echo "not existing dir $1 or not $USER does not have writable permissions, exiting.."
	exit 1
fi

#check rights
if [ ! -w$REPO_DIR ] ; then
	echo "not writable permissions, exiting.."
	exit 1
fi

#clean up
if [ ! -z `repomanage --keep=$KEEP_PKGS --old $REPO_DIR` ]; then
	rm $(repomanage --keep=$KEEP_PKGS --old $REPO_DIR)
fi

#resigning
GPG_NAME=`gpg --list-keys | grep "$GPGKEY" -1 | grep uid | sed "s/uid *//"`
if [ ! -z "$GPG_NAME" ]; then
        GPG_LC=`echo $GPGKEY  | awk '{print tolower($0)}'`

        find $REPO_DIR -type f -name "*.rpm"  | while read ENTRY
        do
          RES=`rpm -K "$ENTRY"  -v | grep OK | grep $GPG_LC`
          if [ $? -ne 0 ]; then
                #echo "signing $ENTRY by KEY:$GPGKEY  NAME:$GPG_NAME"
                rpm --addsign -D "_signature gpg" -D "_gpg_name $GPG_NAME"  "$ENTRY"
          fi
        done
fi

#generate repo
createrepo  $REPO_DIR
if [ $? -ne 0 ]; then
	echo "createrepo failed."
	exit 1
fi

