'\" t
.\"     Title: jss-xml-validator
.\"    Author: Miroslav Safr <miroslav.safr@gmail.com>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 20140305_1713
.\"    Manual: Support scripts for releasing and CI environemnts
.\"    Source: jenkins-support-scripts 1.2.0
.\"  Language: English
.\"
.TH "JSS\-XML\-VALIDATOR" "1" "20140305_1713" "jenkins-support-scripts 1.2.0" "Support scripts for releasing"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
jss-xml-validator \- Recursive validation for xml files (xml)
.SH "SYNOPSIS"
.HP \w'\fBjss\-xml\-validator\ [REPO_DIR]\ [OPTIONS]\fR\ 'u
\fBjss\-xml\-validator [REPO_DIR] [OPTIONS]\fR [\-h\ \-\-help] [\-ext\ \-\-extension\ <ext>] [\-dtd\ <dtd\-file>] [\-xsd\ <xsd\-file>]
.SH "DESCRIPTION"
.PP
Recursive validation for xml files xml) using wrapped xmllint\&. By default without dtd/xsd is performed only syntax check\&.
.SH "REPO_DIR"
.PP
Root directory where xml files are\&. If not specified uses current directory\&.
.SH "OPTIONS"
.PP
\-h \-\-help
.RS 4
Prints command line help\&.
.RE
.PP
\-ext \-\-extension <ext>
.RS 4
Choose file extension to search for (default xml)\&.
.RE
.PP
\-dtd <dtd\-file>
.RS 4
Use DTD (Document Type Definition)\&.
.RE
.PP
\-xsd <xsd\-file>
.RS 4
Use XSD (W3C XML schema valiadtion)\&.
.RE
.SH "EXAMPLES"
.PP

.sp
.if n \{\
.RS 4
.\}
.nf
        #one file syntax check
        jss\-xml\-validator my\&.xml
        
        #xml recursive syntax check
        jss\-xml\-validator \&./project\-folder\-with\-xmls/
        
        #xml recursive dtd check
        jss\-xml\-validator \-dtd \&./my\-dtd\&.dtd \&./project\-folder\-with\-xmls/
       
        #xml recursive xsd check
        jss\-xml\-validator \-dtd \&./my\-xsd\&.xsd \&./project\-folder\-with\-xmls/
      
.fi
.if n \{\
.RE
.\}
.sp
.SH "SEE ALSO"
.PP
jenkins\-support\-scripts(1), xmllint(1)\&.
\m[blue]\fB\%http://safrm.net/projects/jenkins-support-scripts/\fR\m[]
.SH "AUTHOR"
.PP
Miroslav Šafr <miroslav\&.safr@gmail\&.com>
.SH "LICENSE"
.PP
LGPL2
.SH "AUTHOR"
.PP
\fBMiroslav Safr\fR <\&miroslav\&.safr@gmail\&.com\&>
.RS 4
Author and maintainer
.RE
