'\" t
.\"     Title: jss-xml-validator
.\"    Author: Miroslav Safr <miroslav.safr@gmail.com>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 20140305_1713
.\"    Manual: Support scripts for releasing and CI environemnts
.\"    Source: jenkins-support-scripts 1.2.0
.\"  Language: English
.\"
.TH "JSS\-XML\-VALIDATOR" "1" "20140305_1713" "jenkins-support-scripts 1.2.0" "Support scripts for releasing"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
jss-docs-update \- Docbook based html and manpages docs updater
.SH "SYNOPSIS"
.HP \w'\fBjss\-docs\-update\ [REPO_DIR]\ [OPTIONS]\fR\ 'u
\fBjss\-docs\-update [REPO_DIR] [OPTIONS]\fR [\-\-help] [\-sv\ \-\-set\-version\ <my\-version>] [\-V\ \-\-version]
.SH "DESCRIPTION"
.PP
Docbook based html and manpages docs updater\&. Directory structure: DOC_DIR/file\&.X\&.xml DOC_DIR/htmlpages/file\&.html DOC_DIR/manpages/file\&.X
.SH "DOC_DIR"
.PP
Doc directory with sources in docbook xml format\&.
.SH "OPTIONS"
.PP
\-h \-\-help
.RS 4
Prints command line help\&.
.RE
.PP
\-sv \-\-set\-version <my\-version>
.RS 4
Project version is taken from argument <my\-version> instead of git tag\&.
.RE
.PP
\-V \-\-version
.RS 4
Prints version of scripts\&.
.RE
.SH "SEE ALSO"
.PP
jenkins\-support\-scripts(1)\&.
\m[blue]\fB\%http://safrm.net/projects/jenkins-support-scripts/\fR\m[]
.SH "AUTHOR"
.PP
Miroslav Šafr <miroslav\&.safr@gmail\&.com>
.SH "LICENSE"
.PP
LGPL2
.SH "AUTHOR"
.PP
\fBMiroslav Safr\fR <\&miroslav\&.safr@gmail\&.com\&>
.RS 4
Author and maintainer
.RE
