'\" t
.\"     Title: jss-debrepo-update
.\"    Author: Miroslav Safr <miroslav.safr@gmail.com>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 20140306_1704
.\"    Manual: Support scripts for releasing and CI environemnts
.\"    Source: jenkins-support-scripts EBVERSION
.\"  Language: English
.\"
.TH "JSS\-DEBREPO\-UPDATE" "1" "20140306_1704" "jenkins-support-scripts EBVERS" "Support scripts for releasing"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
jss-debrepo-update \- Update debaian repository
.SH "SYNOPSIS"
.HP \w'\fBjss\-debrepo\-update\ [REPO_DIR]\ \&.\&.\&.\ [OPTIONS]\ \fR\ 'u
\fBjss\-debrepo\-update [REPO_DIR] \&.\&.\&. [OPTIONS] \fR [\-v\ \-\-verbose] [\-n\ \-\-name\ <gpg\-name>]
.SH "DESCRIPTION"
.PP
Resign non signed debian packages and files (\&.deb,\&.changes,\&.dsc) by specified gpg signature\&. Uses gpg profile from (export GPGKEY=\&.\&.) or first one if empty or (from name given by argument \-n <gpg\-name>) \&. Than regenerates repository\&.
.SH "REPO_DIR"
.PP
Root directory of deb repo\&. If not specified uses current directory\&.
.SH "OPTIONS"
.PP
\-v \-\-verbose
.RS 4
Prints more output\&.
.RE
.PP
\-n \-\-name
.RS 4
Uses GPG key from specified name\&.
.RE
.SH "SEE ALSO"
.PP
jenkins\-support\-scripts(1)\&.
\m[blue]\fB\%http://safrm.net/projects/jenkins-support-scripts/\fR\m[]
.SH "AUTHOR"
.PP
Miroslav Šafr <miroslav\&.safr@gmail\&.com>
.SH "LICENSE"
.PP
LGPL2
.SH "AUTHOR"
.PP
\fBMiroslav Safr\fR <\&miroslav\&.safr@gmail\&.com\&>
.RS 4
Author and maintainer
.RE
